---
# file: Install-Patches.yml

- hosts: all
  vars:
    win_updates_categories:
      - CriticalUpdates
      - SecurityUpdates
  tasks:
  # Check if there are missing updates
  - name: Check for missing updates.
    win_updates:
      state: searched
      category_names: "{{ win_updates_categories }}"
    register: update_count
    ignore_errors: yes

  - name: Reboot if needed
    ansible:
      windows:
        win_reboot:
          when: update_count.reboot_required
            reboot_timeout: 120

  - name: Install missing updates.
    win_updates:
      category_names: "{{ win_updates_categories }}"
    register: update_result

  - name: Reboot if needed
    ansible:
      windows:
        win_reboot:
          when: update_result.reboot_required
            reboot_timeout: 120
