--- 
- hosts: all
  any_errors_fatal: false
  vars:
    win_updates_categories:
      - CriticalUpdates
      - SecurityUpdates

  tasks:
    - name: "Check for missing patches"
      register: update_count
      win_updates:
        category_names: "{{ win_updates_categories }}"
        state: searched
      ignore_errors: yes

    - name: "Reboot if needed"
      win_reboot:
        when: update_count.reboot_required
      reboot_timeout: 120
      ignore_errors: yes

    - name: "Install missing updates."
      register: update_result
      win_updates:
        category_names: "{{ win_updates_categories }}"

    - name: "Reboot if needed after patching"
      win_reboot:
        when: update_result.reboot_required
      reboot_timeout: 120
      ignore_errors: yes
